name: Build and publish Python package to PyPI

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        #with:
          #user: __token__
          #password: ${{ secrets.PYPI_API_TOKEN }}
